// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import QuartzCore;
@import UIKit;
@import Foundation;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSDictionary;

SWIFT_CLASS("_TtC14MercadoPagoSDK10AmountInfo")
@interface AmountInfo : NSObject
+ (AmountInfo * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end

@class Cause;

SWIFT_CLASS("_TtC14MercadoPagoSDK12ApiException")
@interface ApiException : NSObject
@property (nonatomic, strong) Cause * _Null_unspecified cause;
@property (nonatomic, copy) NSString * _Null_unspecified error;
@property (nonatomic, copy) NSString * _Null_unspecified message;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK7BinMask")
@interface BinMask : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified exclusionPattern;
@property (nonatomic, copy) NSString * _Null_unspecified installmentsPattern;
@property (nonatomic, copy) NSString * _Null_unspecified pattern;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (BinMask * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end


@interface CALayer (SWIFT_EXTENSION(MercadoPagoSDK))
@end

@class NSCoder;

SWIFT_CLASS("_TtC14MercadoPagoSDK27CallbackCancelTableViewCell")
@interface CallbackCancelTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class Cardholder;
@class NSDate;
@class NSNumber;
@class PaymentMethod;
@class Issuer;
@class SecurityCode;

SWIFT_CLASS("_TtC14MercadoPagoSDK4Card")
@interface Card : NSObject
@property (nonatomic, strong) Cardholder * _Nullable cardHolder;
@property (nonatomic, copy) NSString * _Nullable customerId;
@property (nonatomic, strong) NSDate * _Nullable dateCreated;
@property (nonatomic, strong) NSDate * _Nullable dateLastUpdated;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, copy) NSString * _Nullable firstSixDigits;
@property (nonatomic, strong) NSNumber * _Nonnull idCard;
@property (nonatomic, copy) NSString * _Nullable lastFourDigits;
@property (nonatomic, strong) PaymentMethod * _Nullable paymentMethod;
@property (nonatomic, strong) Issuer * _Nullable issuer;
@property (nonatomic, strong) SecurityCode * _Nullable securityCode;
+ (Card * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (BOOL)isSecurityCodeRequired;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK12CardBackView")
@interface CardBackView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIGestureRecognizer;
@class NSBundle;

SWIFT_CLASS("_TtC14MercadoPagoSDK27MercadoPagoUIViewController")
@interface MercadoPagoUIViewController : UIViewController <UIGestureRecognizerDelegate>
@property (nonatomic, copy) void (^ _Nullable callbackCancel)(void);
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotate;
- (UIInterfaceOrientationMask)supportedInterfaceOrientations;
- (void)rightButtonClose;
- (void)rightButtonShoppingCart;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITextField;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CardFormViewController")
@interface CardFormViewController : MercadoPagoUIViewController <UITextFieldDelegate>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)setPMs:(NSArray<PaymentMethod *> * _Nonnull)pms;
- (void)viewDidLoad;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
- (void)verPromociones;
- (void)editingChanged:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13CardFrontView")
@interface CardFrontView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)finishLoad;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardIssuer")
@interface CardIssuer : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified name;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified labels;
- (nonnull instancetype)initWith_id:(NSString * _Nonnull)_id name:(NSString * _Nullable)name labels:(NSArray<NSString *> * _Nonnull)labels OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10CardNumber")
@interface CardNumber : NSObject
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * _Null_unspecified validation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (CardNumber * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end

@class Device;
@class NSError;
@class IdentificationType;
@class NSString;

SWIFT_CLASS("_TtC14MercadoPagoSDK9CardToken")
@interface CardToken : NSObject
@property (nonatomic, copy) NSString * _Nullable cardNumber;
@property (nonatomic, copy) NSString * _Nullable securityCode;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, strong) Cardholder * _Nullable cardholder;
@property (nonatomic, strong) Device * _Nullable device;
- (nonnull instancetype)initWithCardNumber:(NSString * _Nullable)cardNumber expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear securityCode:(NSString * _Nullable)securityCode cardholderName:(NSString * _Nonnull)cardholderName docType:(NSString * _Nonnull)docType docNumber:(NSString * _Nonnull)docNumber OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)normalizeCardNumber:(NSString * _Nullable)number;
- (BOOL)validate;
- (BOOL)validate:(BOOL)includeSecurityCode;
- (NSError * _Nullable)validateCardNumber;
- (NSError * _Nullable)validateCardNumber:(PaymentMethod * _Nonnull)paymentMethod;
- (NSError * _Nullable)validateSecurityCode;
- (NSError * _Nullable)validateSecurityCode:(NSString * _Nullable)securityCode;
- (NSError * _Nullable)validateSecurityCodeWithPaymentMethod:(PaymentMethod * _Nonnull)paymentMethod;
- (NSError * _Nullable)validateSecurityCodeWithPaymentMethod:(NSString * _Nonnull)securityCode paymentMethod:(PaymentMethod * _Nonnull)paymentMethod bin:(NSString * _Nonnull)bin;
- (NSError * _Nullable)validateExpiryDate;
- (NSError * _Nullable)validateExpiryDate:(NSInteger)month year:(NSInteger)year;
- (BOOL)validateExpMonth:(NSInteger)month;
- (BOOL)validateExpYear:(NSInteger)year;
- (NSError * _Nullable)validateIdentification;
- (NSError * _Nullable)validateIdentificationType;
- (NSError * _Nullable)validateIdentificationNumber;
- (NSError * _Nullable)validateIdentificationNumber:(IdentificationType * _Nullable)identificationType;
- (NSError * _Nullable)validateCardholderName;
- (BOOL)hasYearPassed:(NSInteger)year;
- (BOOL)hasMonthPassed:(NSInteger)year month:(NSInteger)month;
- (NSInteger)normalizeYear:(NSInteger)year;
- (BOOL)checkLuhn:(NSString * _Nonnull)cardNumber;
- (NSString * _Nullable)getBin;
- (NSString * _Nonnull)toJSONString;
- (NSString * _Nonnull)getNumberFormated;
- (NSString * _Nonnull)getExpirationDateFormated;
@end

@class Identification;

SWIFT_CLASS("_TtC14MercadoPagoSDK10Cardholder")
@interface Cardholder : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) Identification * _Nullable identification;
+ (Cardholder * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Cause")
@interface Cause : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified code;
@property (nonatomic, copy) NSString * _Null_unspecified _description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Item;
@class Payer;
@class PaymentPreference;
@class UIImage;

SWIFT_CLASS("_TtC14MercadoPagoSDK18CheckoutPreference")
@interface CheckoutPreference : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSArray<Item *> * _Nullable items;
@property (nonatomic, strong) Payer * _Null_unspecified payer;
@property (nonatomic, strong) PaymentPreference * _Null_unspecified paymentPreference;
@property (nonatomic, copy) NSString * _Nonnull siteId;
@property (nonatomic, strong) UIImage * _Nullable choImage;
- (NSString * _Nullable)validate;
- (nonnull instancetype)initWithItems:(NSArray<Item *> * _Nonnull)items payer:(Payer * _Nullable)payer paymentMethods:(PaymentPreference * _Nullable)paymentMethods OBJC_DESIGNATED_INITIALIZER;
+ (CheckoutPreference * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (BOOL)loadingImageWithCallback:(void (^ _Nullable)(void))callback;
- (NSString * _Nonnull)toJSONString;
- (double)getAmount;
- (NSInteger)getInstallments;
- (PaymentPreference * _Nonnull)getPaymentPreference;
- (NSSet<NSString *> * _Nullable)getExcludedPaymentTypesIds;
- (NSInteger)getDefaultInstallments;
- (NSInteger)getMaxAcceptedInstallments;
- (NSSet<NSString *> * _Nullable)getExcludedPaymentMethodsIds;
- (NSString * _Nullable)getDefaultPaymentMethodId;
- (NSString * _Nonnull)getTitle;
- (NSString * _Nonnull)getCurrencyId;
- (NSString * _Nonnull)getPictureUrl;
@end

@class UITableView;
@class NSIndexPath;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CheckoutViewController")
@interface CheckoutViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK34CongratsPaymentMethodTableViewCell")
@interface CongratsPaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end

@class Payment;

SWIFT_CLASS("_TtC14MercadoPagoSDK22CongratsViewController")
@interface CongratsViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITextFieldDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)declareAndInitCells;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (void)_setTitle:(Payment * _Nonnull)payment;
- (void)_setIcon:(Payment * _Nonnull)payment;
- (void)setDescription:(Payment * _Nonnull)payment;
- (void)setAmount:(Payment * _Nonnull)payment;
- (void)setPaymentId:(Payment * _Nonnull)payment;
- (void)setPaymentMethodDescription:(Payment * _Nonnull)payment;
- (void)setDateCreated:(Payment * _Nonnull)payment;
- (void)setButtonText:(Payment * _Nonnull)payment;
- (void)submitForm;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Currency")
@interface Currency : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified _description;
@property (nonatomic, copy) NSString * _Null_unspecified symbol;
@property (nonatomic) NSInteger decimalPlaces;
@property (nonatomic, copy) NSString * _Null_unspecified decimalSeparator;
@property (nonatomic, copy) NSString * _Null_unspecified thousandsSeparator;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWith_id:(NSString * _Nonnull)_id description:(NSString * _Nonnull)description symbol:(NSString * _Nonnull)symbol decimalPlaces:(NSInteger)decimalPlaces decimalSeparator:(NSString * _Nonnull)decimalSeparator thousandSeparator:(NSString * _Nonnull)thousandSeparator OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)getCurrencySymbolOrDefault;

/// <ul><li><ul><li></li></ul>Default values are ARS values<ul><li></li><li></li></ul></li></ul>
- (NSString * _Nonnull)getThousandsSeparatorOrDefault;
- (NSString * _Nonnull)getDecimalSeparatorOrDefault;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8Customer")
@interface Customer : NSObject
@property (nonatomic, copy) NSArray<Card *> * _Nullable cards;
@property (nonatomic, strong) NSNumber * _Nullable defaultCard;
@property (nonatomic, copy) NSString * _Nullable _description;
@property (nonatomic, strong) NSDate * _Nullable dateCreated;
@property (nonatomic, strong) NSDate * _Nullable dateLastUpdated;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable _id;
@property (nonatomic, strong) Identification * _Nullable identification;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, strong) NSDictionary * _Nullable metadata;
@property (nonatomic, strong) NSDate * _Nullable registrationDate;
+ (Customer * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27CustomerCardsViewController")
@interface CustomerCardsViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nonnull instancetype)initWithCards:(NSArray<Card *> * _Nullable)cards callback:(void (^ _Nonnull)(Card * _Nullable selectedCard))callback OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)loadCards;
- (void)newCard;
@end

@class Fingerprint;

SWIFT_CLASS("_TtC14MercadoPagoSDK6Device")
@interface Device : NSObject
@property (nonatomic, strong) Fingerprint * _Null_unspecified fingerprint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18ErrorTableViewCell")
@interface ErrorTableViewCell : UITableViewCell
@property (nonatomic) CGFloat height;
- (void)setError:(NSString * _Nullable)error;
- (void)focus;
- (BOOL)hasError;
- (CGFloat)getHeight;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class MPError;

SWIFT_CLASS("_TtC14MercadoPagoSDK19ErrorViewController")
@interface ErrorViewController : MercadoPagoUIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
@property (nonatomic, copy) void (^ _Null_unspecified exitErrorCallback)(void);
- (nonnull instancetype)initWithError:(MPError * _Null_unspecified)error callback:(void (^ _Nullable)(void))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK10FeesDetail")
@interface FeesDetail : NSObject
@property (nonatomic) double amount;
@property (nonatomic) double amountRefunded;
@property (nonatomic, copy) NSString * _Null_unspecified feePayer;
@property (nonatomic, copy) NSString * _Null_unspecified type;
+ (FeesDetail * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11Fingerprint")
@interface Fingerprint : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable fingerprint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
- (NSDictionary<NSString *, id> * _Nonnull)deviceFingerprint;
- (NSArray * _Nullable)devicesID;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18MercadoPagoService")
@interface MercadoPagoService : NSObject
- (void)request:(NSString * _Nonnull)uri params:(NSString * _Nullable)params body:(id _Nullable)body method:(NSString * _Nonnull)method headers:(NSDictionary * _Nullable)headers cache:(BOOL)cache success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end

@class SavedCardToken;

SWIFT_CLASS("_TtC14MercadoPagoSDK14GatewayService")
@interface GatewayService : MercadoPagoService
- (void)getToken:(NSString * _Nonnull)url method:(NSString * _Nonnull)method public_key:(NSString * _Nonnull)public_key savedCardToken:(SavedCardToken * _Nonnull)savedCardToken success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)getToken:(NSString * _Nonnull)url method:(NSString * _Nonnull)method public_key:(NSString * _Nonnull)public_key cardToken:(CardToken * _Nonnull)cardToken success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16GenericErrorView")
@interface GenericErrorView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setErrorMessage:(NSString * _Nonnull)errorMessage;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11MPTextField")
@interface MPTextField : UITextField
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class MPLabel;


/// A TextFieldEffects object is a control that displays editable text and contains the boilerplates to setup unique animations for text entrey and display. You typically use this class the same way you use UITextField.
SWIFT_CLASS("_TtC14MercadoPagoSDK16TextFieldEffects")
@interface TextFieldEffects : MPTextField

/// UILabel that holds all the placeholder information
@property (nonatomic, readonly, strong) MPLabel * _Nonnull placeholderLabel;

/// Creates all the animations that are used to leave the textfield in the "entering text" state.
- (void)animateViewsForTextEntry;

/// Creates all the animations that are used to leave the textfield in the "display input text" state.
- (void)animateViewsForTextDisplay;

/// Draws the receiver’s image within the passed-in rectangle.
///
/// \param rect The portion of the view’s bounds that needs to be updated.
- (void)drawViewsForRect:(CGRect)rect;
- (void)updateViewsForBoundsChange:(CGRect)bounds;
- (void)drawRect:(CGRect)rect;
- (void)drawPlaceholderInRect:(CGRect)rect;
@property (nonatomic, copy) NSString * _Nullable text;
- (void)willMoveToSuperview:(UIView * _Null_unspecified)newSuperview;

/// The textfield has started an editing session.
- (void)textFieldDidBeginEditing;

/// The textfield has ended an editing session.
- (void)textFieldDidEndEditing;
- (void)prepareForInterfaceBuilder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;


/// An HoshiTextField is a subclass of the TextFieldEffects object, is a control that displays an UITextField with a customizable visual effect around the lower edge of the control.
SWIFT_CLASS("_TtC14MercadoPagoSDK14HoshiTextField")
@interface HoshiTextField : TextFieldEffects

/// The color of the border when it has no content.
///
/// This property applies a color to the lower edge of the control. The default value for this property is a clear color.
@property (nonatomic, strong) UIColor * _Nullable borderInactiveColor;

/// The color of the border when it has content.
///
/// This property applies a color to the lower edge of the control. The default value for this property is a clear color.
@property (nonatomic, strong) UIColor * _Nullable borderActiveColor;

/// The color of the placeholder text.
///
/// This property applies a color to the complete placeholder string. The default value for this property is a black color.
@property (nonatomic, strong) UIColor * _Nonnull placeholderColor;

/// The scale of the placeholder font.
///
/// This property determines the size of the placeholder label relative to the font size of the text field.
@property (nonatomic) CGFloat placeholderFontScale;
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic) CGRect bounds;
- (void)drawViewsForRect:(CGRect)rect;
- (void)animateViewsForTextEntry;
- (void)animateViewsForTextDisplay;
- (CGRect)editingRectForBounds:(CGRect)bounds;
- (CGRect)textRectForBounds:(CGRect)bounds;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14Identification")
@interface Identification : NSObject
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable number;
- (nonnull instancetype)initWithType:(NSString * _Nullable)type number:(NSString * _Nullable)number OBJC_DESIGNATED_INITIALIZER;
+ (Identification * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22IdentificationCardView")
@interface IdentificationCardView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IdentificationService")
@interface IdentificationService : MercadoPagoService
- (void)getIdentificationTypes:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nullable)public_key privateKey:(NSString * _Nullable)privateKey success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18IdentificationType")
@interface IdentificationType : NSObject
@property (nonatomic, copy) NSString * _Nullable _id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) NSInteger minLength;
@property (nonatomic) NSInteger maxLength;
+ (IdentificationType * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPickerView;

SWIFT_CLASS("_TtC14MercadoPagoSDK28IdentificationViewController")
@interface IdentificationViewController : MercadoPagoUIViewController <UIPickerViewDelegate, UIPickerViewDataSource, UITextFieldDelegate>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nonnull instancetype)initWithCallback:(void (^ _Nonnull)(Identification * _Nonnull identification))callback OBJC_DESIGNATED_INITIALIZER;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
- (void)editingChanged:(UITextField * _Nonnull)textField;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)donePicker;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
- (NSString * _Null_unspecified)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end

@class PayerCost;

SWIFT_CLASS("_TtC14MercadoPagoSDK11Installment")
@interface Installment : NSObject
@property (nonatomic, strong) Issuer * _Null_unspecified issuer;
@property (nonatomic, copy) NSArray<PayerCost *> * _Null_unspecified payerCosts;
@property (nonatomic, copy) NSString * _Null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * _Null_unspecified paymentTypeId;
+ (Installment * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (PayerCost * _Nullable)containsInstallment:(NSInteger)installment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24InstallmentTableViewCell")
@interface InstallmentTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * _Nonnull)payerCost amount:(double)amount;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26InstallmentsViewController")
@interface InstallmentsViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11Instruction")
@interface Instruction : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull accreditationMessage;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified info;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable secondaryInfo;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tertiaryInfo;
+ (Instruction * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16InstructionsInfo")
@interface InstructionsInfo : NSObject
+ (InstructionsInfo * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19InstructionsService")
@interface InstructionsService : MercadoPagoService
@property (nonatomic, readonly, copy) NSString * _Nonnull MP_INSTRUCTIONS_URI;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)getInstructions:(NSInteger)paymentId paymentTypeId:(NSString * _Nullable)paymentTypeId success:(void (^ _Nonnull)(InstructionsInfo * _Nonnull instructionsInfo))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26InstructionsViewController")
@interface InstructionsViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Issuer")
@interface Issuer : NSObject
@property (nonatomic, strong) NSNumber * _Nullable _id;
@property (nonatomic, copy) NSString * _Nullable name;
+ (Issuer * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24IssuerCardViewController")
@interface IssuerCardViewController : MercadoPagoUIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nonnull instancetype)initWithPaymentMethod:(PaymentMethod * _Nonnull)paymentMethod cardToken:(CardToken * _Nonnull)cardToken issuerList:(NSArray<Issuer *> * _Nullable)issuerList callback:(void (^ _Nonnull)(Issuer * _Nonnull issuer))callback OBJC_DESIGNATED_INITIALIZER;
- (void)viewWillAppear:(BOOL)animated;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)updateCardSkin;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19IssuerTableViewCell")
@interface IssuerTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithIssuer:(Issuer * _Nonnull)issuer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21IssuersViewController")
@interface IssuersViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK4Item")
@interface Item : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic) NSInteger quantity;
@property (nonatomic) double unitPrice;
@property (nonatomic, copy) NSString * _Null_unspecified title;
@property (nonatomic, copy) NSString * _Null_unspecified currencyId;
@property (nonatomic, copy) NSString * _Null_unspecified categoryId;
@property (nonatomic, copy) NSString * _Null_unspecified pictureUrl;
- (BOOL)validate;
- (nonnull instancetype)initWith_id:(NSString * _Nullable)_id title:(NSString * _Nullable)title quantity:(NSInteger)quantity unitPrice:(double)unitPrice OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
+ (Item * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK8MPButton")
@interface MPButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class Setting;

SWIFT_CLASS("_TtC14MercadoPagoSDK25MPCardNumberTableViewCell")
@interface MPCardNumberTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet MPTextField * _Null_unspecified cardNumberTextField;
@property (nonatomic, strong) Setting * _Null_unspecified setting;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getCardNumber;
- (void)setIcon:(NSString * _Nullable)pmId;
- (void)_setSetting:(Setting * _Null_unspecified)setting;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPCardholderNameTableViewCell")
@interface MPCardholderNameTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet MPTextField * _Null_unspecified cardholderNameTextField;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getCardholderName;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK7MPError")
@interface MPError : NSObject
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, copy) NSString * _Nonnull messageDetail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (MPError * _Nonnull)convertFrom:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29MPExpirationDateTableViewCell")
@interface MPExpirationDateTableViewCell : ErrorTableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet MPTextField * _Null_unspecified expirationDateTextField;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)getExpirationMonth;
- (NSInteger)getExpirationYear;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
@end

@class VaultViewController;
@class MPNavigationController;
@class Token;

SWIFT_CLASS("_TtC14MercadoPagoSDK13MPFlowBuilder")
@interface MPFlowBuilder : NSObject
+ (VaultViewController * _Nonnull)startVaultViewController:(double)amount paymentPreference:(PaymentPreference * _Nullable)paymentPreference callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull paymentMethod, NSString * _Nullable tokenId, Issuer * _Nullable issuer, NSInteger installments))callback;
+ (MPNavigationController * _Nonnull)startCheckoutViewController:(NSString * _Nonnull)preferenceId callback:(void (^ _Nonnull)(Payment * _Nonnull))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel;
+ (MPNavigationController * _Nonnull)startPaymentVaultViewController:(double)amount paymentPreference:(PaymentPreference * _Nullable)paymentPreference callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull paymentMethod, Token * _Nullable token, Issuer * _Nullable issuer, PayerCost * _Nullable payerCost))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel;
+ (MPNavigationController * _Nonnull)startCardFlow:(PaymentPreference * _Nullable)paymentPreference amount:(double)amount paymentMethods:(NSArray<PaymentMethod *> * _Nullable)paymentMethods token:(Token * _Nullable)token callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull paymentMethod, Token * _Nullable token, Issuer * _Nullable issuer, PayerCost * _Nullable payerCost))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPInstallmentsTableViewCell")
@interface MPInstallmentsTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithPayerCost:(PayerCost * _Nullable)payerCost amount:(double)amount;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK7MPLabel")
@interface MPLabel : UILabel
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22MPNavigationController")
@interface MPNavigationController : UINavigationController
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9MPPayment")
@interface MPPayment : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified email;
@property (nonatomic, copy) NSString * _Null_unspecified preferenceId;
@property (nonatomic, copy) NSString * _Null_unspecified publicKey;
@property (nonatomic, copy) NSString * _Null_unspecified paymentMethodId;
@property (nonatomic) NSInteger installments;
@property (nonatomic, copy) NSString * _Nullable issuerId;
@property (nonatomic, copy) NSString * _Nullable tokenId;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK33MPPaymentMethodEmptyTableViewCell")
@interface MPPaymentMethodEmptyTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28MPPaymentMethodTableViewCell")
@interface MPPaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)fillWithCard:(Card * _Nullable)card;
- (void)fillWithCardTokenAndPaymentMethod:(CardToken * _Nullable)card paymentMethod:(PaymentMethod * _Nullable)paymentMethod;
- (void)fillWithPaymentMethod:(PaymentMethod * _Nullable)paymentMethod;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27MPSecurityCodeTableViewCell")
@interface MPSecurityCodeTableViewCell : ErrorTableViewCell
@property (nonatomic, weak) IBOutlet MPTextField * _Null_unspecified securityCodeTextField;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getSecurityCode;
- (void)fillWithPaymentMethod:(PaymentMethod * _Nonnull)pm;
@end

@class Promo;
@class MerchantPayment;

SWIFT_CLASS("_TtC14MercadoPagoSDK17MPServicesBuilder")
@interface MPServicesBuilder : NSObject
+ (void)createNewCardToken:(CardToken * _Nonnull)cardToken success:(void (^ _Nonnull)(Token * _Nullable token))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)createToken:(SavedCardToken * _Nonnull)savedCardToken success:(void (^ _Nonnull)(Token * _Nullable token))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)getPaymentMethods:(void (^ _Nonnull)(NSArray<PaymentMethod *> * _Nullable paymentMethods))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)getIdentificationTypes:(void (^ _Nonnull)(NSArray<IdentificationType *> * _Nullable identificationTypes))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)getInstallments:(NSString * _Nullable)bin amount:(double)amount issuer:(Issuer * _Nullable)issuer paymentMethodId:(NSString * _Nonnull)paymentMethodId success:(void (^ _Nonnull)(NSArray<Installment *> * _Nullable installments))success failure:(void (^ _Nonnull)(NSError * _Nonnull error))failure;
+ (void)getIssuers:(PaymentMethod * _Nonnull)paymentMethod bin:(NSString * _Nullable)bin success:(void (^ _Nonnull)(NSArray<Issuer *> * _Nullable issuers))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)getPromos:(void (^ _Nonnull)(NSArray<Promo *> * _Nullable promos))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)createPayment:(NSString * _Nonnull)merchantBaseUrl merchantPaymentUri:(NSString * _Nonnull)merchantPaymentUri payment:(MerchantPayment * _Nonnull)payment success:(void (^ _Nonnull)(Payment * _Nonnull payment))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)getInstructions:(NSInteger)paymentId paymentTypeId:(NSString * _Nullable)paymentTypeId success:(void (^ _Nonnull)(InstructionsInfo * _Nonnull instructionsInfo))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)getPreference:(NSString * _Nonnull)preferenceId success:(void (^ _Nonnull)(CheckoutPreference * _Nonnull preference))success failure:(void (^ _Nonnull)(NSError * _Nonnull error))failure;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NewCardViewController;
@class PaymentMethodsViewController;
enum CongratsState : NSInteger;
@class PaymentCongratsViewController;
@class PromoViewController;
@class PayerCostViewController;

SWIFT_CLASS("_TtC14MercadoPagoSDK13MPStepBuilder")
@interface MPStepBuilder : NSObject
+ (CustomerCardsViewController * _Nonnull)startCustomerCardsStep:(NSArray<Card *> * _Nonnull)cards callback:(void (^ _Nonnull)(Card * _Nullable selectedCard))callback;
+ (NewCardViewController * _Nonnull)startNewCardStep:(PaymentMethod * _Nonnull)paymentMethod requireSecurityCode:(BOOL)requireSecurityCode callback:(void (^ _Nonnull)(CardToken * _Nonnull cardToken))callback;
+ (PaymentMethodsViewController * _Nonnull)startPaymentMethodsStepWithPreference:(PaymentPreference * _Nullable)paymentPreference callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull paymentMethod))callback;
+ (PaymentMethodsViewController * _Nonnull)startPaymentMethodsStep:(NSSet<NSString *> * _Nonnull)supportedPaymentTypes callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull paymentMethod))callback;
+ (InstallmentsViewController * _Nonnull)startInstallmentsStep:(NSArray<PayerCost *> * _Nullable)payerCosts paymentPreference:(PaymentPreference * _Nullable)paymentPreference amount:(double)amount issuer:(Issuer * _Nullable)issuer paymentMethodId:(NSString * _Nullable)paymentMethodId callback:(void (^ _Nonnull)(PayerCost * _Nullable payerCost))callback;
+ (CongratsViewController * _Nonnull)startCongratsStep:(Payment * _Nonnull)payment paymentMethod:(PaymentMethod * _Nonnull)paymentMethod;
+ (MercadoPagoUIViewController * _Nonnull)startPaymentResultStep:(Payment * _Nonnull)payment paymentMethod:(PaymentMethod * _Nonnull)paymentMethod callback:(void (^ _Nonnull)(Payment * _Nonnull payment, enum CongratsState status))callback;
+ (PaymentCongratsViewController * _Nonnull)startPaymentCongratsStep:(Payment * _Nonnull)payment paymentMethod:(PaymentMethod * _Nonnull)paymentMethod callback:(void (^ _Nonnull)(Payment * _Nonnull payment, enum CongratsState status))callback;
+ (InstructionsViewController * _Nonnull)startInstructionsStep:(Payment * _Nonnull)payment paymentTypeId:(NSString * _Nonnull)paymentTypeId callback:(void (^ _Nonnull)(Payment * _Nonnull payment, enum CongratsState status))callback;
+ (PromoViewController * _Nonnull)startPromosStep:(void (^ _Nullable)(void))callback;
+ (MPNavigationController * _Nonnull)startCreditCardForm:(PaymentPreference * _Nullable)paymentSettings amount:(double)amount paymentMethods:(NSArray<PaymentMethod *> * _Nullable)paymentMethods token:(Token * _Nullable)token callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull paymentMethod, Token * _Nullable token, Issuer * _Nullable issuer))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel;
+ (PayerCostViewController * _Nonnull)startPayerCostForm:(PaymentMethod * _Nullable)paymentMethod issuer:(Issuer * _Nullable)issuer token:(Token * _Nonnull)token amount:(double)amount paymentPreference:(PaymentPreference * _Nullable)paymentPreference installment:(Installment * _Nullable)installment callback:(void (^ _Nonnull)(PayerCost * _Nullable payerCost))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel;
+ (IdentificationViewController * _Nonnull)startIdentificationForm:(void (^ _Nonnull)(Identification * _Nullable identification))callback;
+ (IssuersViewController * _Nonnull)startIssuersStep:(PaymentMethod * _Nonnull)paymentMethod callback:(void (^ _Nonnull)(Issuer * _Nonnull issuer))callback;
+ (IssuerCardViewController * _Nonnull)startIssuerForm:(PaymentMethod * _Nonnull)paymentMethod cardToken:(CardToken * _Nonnull)cardToken issuerList:(NSArray<Issuer *> * _Nullable)issuerList callback:(void (^ _Nonnull)(Issuer * _Nullable issuer))callback;
+ (ErrorViewController * _Nonnull)startErrorViewController:(MPError * _Nonnull)error callback:(void (^ _Nullable)(void))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CongratsState) {
  CongratsStateOK = 0,
  CongratsStateCANCEL_SELECT_OTHER = 1,
  CongratsStateCANCEL_RETRY = 2,
};


@class NSTextContainer;

SWIFT_CLASS("_TtC14MercadoPagoSDK10MPTextView")
@interface MPTextView : UITextView
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9MPToolbar")
@interface MPToolbar : UIToolbar
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21MPUserIdTableViewCell")
@interface MPUserIdTableViewCell : ErrorTableViewCell <UITextFieldDelegate, UIPickerViewDelegate, UIPickerViewDataSource>
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified userIdTypeTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified userIdValueTextField;
@property (nonatomic, strong) IBOutlet UIPickerView * _Null_unspecified pickerIdentificationType;
@property (nonatomic, copy) NSArray<IdentificationType *> * _Nonnull identificationTypes;
@property (nonatomic, strong) IdentificationType * _Nullable identificationType;
- (void)focus;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
- (void)setFormWithIndex:(NSInteger)row;
- (void)awakeFromNib;
- (void)_setIdentificationTypes:(NSArray<IdentificationType *> * _Nullable)identificationTypes;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Null_unspecified)getUserIdType;
- (NSString * _Null_unspecified)getUserIdValue;
- (void)setTextFieldDelegate:(id <UITextFieldDelegate> _Nonnull)delegate;
@end

@class UIAlertView;

SWIFT_CLASS("_TtC14MercadoPagoSDK11MercadoPago")
@interface MercadoPago : NSObject <UIAlertViewDelegate>
+ (NSString * _Nonnull)DEFAULT_FONT_NAME;
+ (NSString * _Nonnull)PUBLIC_KEY;
+ (NSString * _Nonnull)PRIVATE_KEY;
+ (NSInteger)ERROR_KEY_CODE;
+ (NSInteger)ERROR_API_CODE;
+ (NSInteger)ERROR_UNKNOWN_CODE;
+ (NSInteger)ERROR_NOT_INSTALLMENTS_FOUND;
+ (NSInteger)ERROR_PAYMENT;
+ (NSInteger)ERROR_INSTRUCTIONS;
- (NSString * _Null_unspecified)publicKey;
@property (nonatomic, copy) NSString * _Nullable privateKey;
@property (nonatomic, copy) NSString * _Null_unspecified pk;
@property (nonatomic, copy) NSString * _Nullable paymentMethodId;
@property (nonatomic, copy) NSString * _Nullable paymentTypeId;
- (nonnull instancetype)initWithPublicKey:(NSString * _Nonnull)publicKey OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithKeyType:(NSString * _Nullable)keyType key:(NSString * _Nullable)key OBJC_DESIGNATED_INITIALIZER;
- (void)createNewCardToken:(CardToken * _Nonnull)cardToken success:(void (^ _Nonnull)(Token * _Nullable token))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)createToken:(SavedCardToken * _Nonnull)savedCardToken success:(void (^ _Nonnull)(Token * _Nullable token))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)getIdentificationTypes:(void (^ _Nonnull)(NSArray<IdentificationType *> * _Nullable identificationTypes))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)getInstallments:(NSString * _Nonnull)bin amount:(double)amount issuerId:(NSNumber * _Nullable)issuerId paymentTypeId:(NSString * _Nonnull)paymentTypeId success:(void (^ _Nonnull)(NSArray<Installment *> * _Nullable installments))success failure:(void (^ _Nonnull)(NSError * _Nonnull error))failure;
- (void)getIssuers:(NSString * _Nonnull)paymentMethodId success:(void (^ _Nonnull)(NSArray<Issuer *> * _Nullable issuers))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)getPromos:(void (^ _Nonnull)(NSArray<Promo *> * _Nullable promos))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (BOOL)isCardPaymentType:(NSString * _Nonnull)paymentTypeId;
+ (NSBundle * _Nullable)getBundle;
+ (UIImage * _Nullable)getImage:(NSString * _Nullable)name;
+ (CGRect)screenBoundsFixedToPortraitOrientation;
+ (void)showAlertViewWithError:(NSError * _Nullable)error nav:(UINavigationController * _Nullable)nav;
- (void)alertView:(UIAlertView * _Nonnull)alertView clickedButtonAtIndex:(NSInteger)buttonIndex;
+ (UIColor * _Nullable)getColorFor:(PaymentMethod * _Nonnull)paymentMethod;
+ (UIColor * _Nullable)getFontColorFor:(PaymentMethod * _Nonnull)paymentMethod;
+ (UIColor * _Nullable)getEditingFontColorFor:(PaymentMethod * _Nonnull)paymentMethod;
+ (void)createMPPayment:(NSString * _Nonnull)email preferenceId:(NSString * _Nonnull)preferenceId paymentMethod:(PaymentMethod * _Nonnull)paymentMethod token:(Token * _Nullable)token installments:(NSInteger)installments issuer:(Issuer * _Nullable)issuer success:(void (^ _Nonnull)(Payment * _Nonnull payment))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18MercadoPagoContext")
@interface MercadoPagoContext : NSObject
+ (NSString * _Nonnull)PUBLIC_KEY;
+ (NSString * _Nonnull)PRIVATE_KEY;
+ (BOOL)isAuthenticatedUser;
- (NSString * _Null_unspecified)framework;
- (NSString * _Null_unspecified)sdkVersion;
- (NSString * _Null_unspecified)siteId;
+ (void)setSiteID:(NSString * _Nonnull)siteId;
+ (NSString * _Nonnull)getLanguage;
+ (Currency * _Nonnull)getCurrency;
- (NSString * _Null_unspecified)publicKey;
+ (void)setupPrimaryColor:(UIColor * _Nonnull)color complementaryColor:(UIColor * _Nullable)complementaryColor;
+ (void)setupComplementaryColor:(UIColor * _Nonnull)color;
+ (void)setDarkTextColor;
+ (void)setLightTextColor;
+ (void)setPrivateKey:(NSString * _Nonnull)private_key;
+ (void)setPublicKey:(NSString * _Nonnull)public_key;
+ (void)initFlavor1;
+ (void)initFlavor2;
+ (void)initFlavor3;
+ (void)setBaseURL:(NSString * _Nonnull)base_url;
+ (void)setCustomerURI:(NSString * _Nonnull)customer_uri;
+ (void)setPreferenceURI:(NSString * _Nonnull)preference_uri;
+ (void)setPaymentURI:(NSString * _Nonnull)payment_uri;
+ (void)setMerchantAccessToken:(NSString * _Nonnull)merchant_access_token;
+ (NSString * _Nonnull)merchantAccessToken;
+ (NSString * _Nonnull)publicKey;
+ (NSString * _Nonnull)privateKey;
+ (NSString * _Nonnull)baseURL;
+ (NSString * _Nonnull)customerURI;
+ (NSString * _Nonnull)preferenceURI;
+ (NSString * _Nonnull)paymentURI;
+ (NSString * _Nonnull)paymentKey;
+ (void)clearPaymentKey;
+ (NSString * _Nonnull)keyType;
+ (NSString * _Nonnull)keyValue:(BOOL)forcingPublic;
@end




SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantPayment")
@interface MerchantPayment : NSObject
@property (nonatomic, strong) Issuer * _Nullable issuer;
@property (nonatomic, copy) NSString * _Null_unspecified cardTokenId;
@property (nonatomic) NSInteger campaignId;
@property (nonatomic) NSInteger installments;
@property (nonatomic, copy) NSArray<Item *> * _Nullable items;
@property (nonatomic, copy) NSString * _Null_unspecified merchantAccessToken;
@property (nonatomic, strong) PaymentMethod * _Null_unspecified paymentMethod;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItems:(NSArray<Item *> * _Nonnull)items installments:(NSInteger)installments cardIssuer:(Issuer * _Nullable)cardIssuer tokenId:(NSString * _Nonnull)tokenId paymentMethod:(PaymentMethod * _Nonnull)paymentMethod campaignId:(NSInteger)campaignId OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14MerchantServer")
@interface MerchantServer : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (void)getCustomer:(NSString * _Nonnull)merchantBaseUrl success:(void (^ _Nonnull)(Customer * _Nonnull customer))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)createPayment:(MerchantPayment * _Nonnull)payment success:(void (^ _Nonnull)(Payment * _Nonnull payment))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
+ (void)createPreference:(NSDictionary * _Nonnull)params success:(void (^ _Nonnull)(CheckoutPreference * _Nonnull checkoutPreference))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end

@class NSMutableData;

SWIFT_CLASS("_TtC14MercadoPagoSDK15MerchantService")
@interface MerchantService : MercadoPagoService
@property (nonatomic, strong) NSMutableData * _Nonnull data;
- (void)getCustomer:(NSString * _Nonnull)method success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)createPayment:(NSString * _Nonnull)method payment:(MerchantPayment * _Nonnull)payment success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)createMPPayment:(NSString * _Nonnull)method payment:(MPPayment * _Nonnull)payment success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)createPreference:(NSString * _Nonnull)method merchantParams:(NSString * _Nonnull)merchantParams success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11MockBuilder")
@interface MockBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSDictionary (SWIFT_EXTENSION(MercadoPagoSDK))
- (BOOL)isKeyValid:(NSString * _Nonnull)dictKey;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK21NewCardViewController")
@interface NewCardViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (NSInteger)getIndexForObject:(id _Nonnull)object;
- (void)scrollToRow:(NSIndexPath * _Nonnull)indexPath;
- (void)focusAndScrollForIndex:(NSInteger)index;
- (void)prev:(id _Nullable)object;
- (void)next:(id _Nullable)object;
- (void)done:(id _Nullable)object;
- (void)prepareTableView;
- (void)submitForm;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)viewDidLayoutSubviews;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)validateForm:(CardToken * _Nonnull)cardToken;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Order")
@interface Order : NSObject
@property (nonatomic) NSInteger _id;
@property (nonatomic, copy) NSString * _Null_unspecified type;
+ (Order * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Payer")
@interface Payer : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified email;
@property (nonatomic, strong) NSNumber * _Nonnull _id;
@property (nonatomic, strong) Identification * _Null_unspecified identification;
- (nonnull instancetype)initWith_id:(NSNumber * _Nullable)_id email:(NSString * _Nullable)email type:(NSString * _Nullable)type identification:(Identification * _Nullable)identification OBJC_DESIGNATED_INITIALIZER;
+ (Payer * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK9PayerCost")
@interface PayerCost : NSObject
@property (nonatomic) NSInteger installments;
@property (nonatomic) double installmentRate;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified labels;
@property (nonatomic) double minAllowedAmount;
@property (nonatomic) double maxAllowedAmount;
@property (nonatomic, copy) NSString * _Null_unspecified recommendedMessage;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double totalAmount;
- (nonnull instancetype)initWithInstallments:(NSInteger)installments installmentRate:(double)installmentRate labels:(NSArray<NSString *> * _Nonnull)labels minAllowedAmount:(double)minAllowedAmount maxAllowedAmount:(double)maxAllowedAmount recommendedMessage:(NSString * _Null_unspecified)recommendedMessage installmentAmount:(double)installmentAmount totalAmount:(double)totalAmount OBJC_DESIGNATED_INITIALIZER;
+ (PayerCost * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PayerCostViewController")
@interface PayerCostViewController : MercadoPagoUIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)updateCardSkin;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class Refund;
@class TransactionDetails;

SWIFT_CLASS("_TtC14MercadoPagoSDK7Payment")
@interface Payment : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified callForAuthorizeId;
@property (nonatomic, strong) Card * _Null_unspecified card;
@property (nonatomic, copy) NSString * _Null_unspecified currencyId;
@property (nonatomic, strong) NSDate * _Null_unspecified dateApproved;
@property (nonatomic, strong) NSDate * _Null_unspecified dateCreated;
@property (nonatomic, strong) NSDate * _Null_unspecified dateLastUpdated;
@property (nonatomic, copy) NSString * _Null_unspecified _description;
@property (nonatomic, copy) NSString * _Null_unspecified externalReference;
@property (nonatomic, copy) NSArray<FeesDetail *> * _Null_unspecified feesDetails;
@property (nonatomic) NSInteger _id;
@property (nonatomic) NSInteger installments;
@property (nonatomic, strong) NSObject * _Null_unspecified metadata;
@property (nonatomic, strong) NSDate * _Null_unspecified moneyReleaseDate;
@property (nonatomic, copy) NSString * _Null_unspecified notificationUrl;
@property (nonatomic, strong) Order * _Null_unspecified order;
@property (nonatomic, strong) Payer * _Null_unspecified payer;
@property (nonatomic, copy) NSString * _Null_unspecified paymentMethodId;
@property (nonatomic, copy) NSString * _Null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray<Refund *> * _Null_unspecified refunds;
@property (nonatomic, copy) NSString * _Null_unspecified statementDescriptor;
@property (nonatomic, copy) NSString * _Null_unspecified status;
@property (nonatomic, copy) NSString * _Null_unspecified statusDetail;
@property (nonatomic) double transactionAmount;
@property (nonatomic) double transactionAmountRefunded;
@property (nonatomic, strong) TransactionDetails * _Null_unspecified transactionDetails;
@property (nonatomic, copy) NSString * _Null_unspecified collectorId;
@property (nonatomic) double couponAmount;
@property (nonatomic, strong) NSNumber * _Nonnull differentialPricingId;
@property (nonatomic) NSInteger issuerId;
@property (nonatomic, copy) NSString * _Nullable tokenId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Payment * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
+ (NSDate * _Null_unspecified)getDateFromString:(NSString * _Null_unspecified)string;
- (BOOL)isRejected;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK29PaymentCongratsViewController")
@interface PaymentCongratsViewController : MercadoPagoUIViewController <UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSString * _Null_unspecified)methodId;
- (NSString * _Null_unspecified)status;
- (NSString * _Null_unspecified)statusDetail;
- (NSString * _Null_unspecified)typeId;
- (NSString * _Null_unspecified)installments;
- (NSString * _Null_unspecified)issuerId;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK24PaymentDateTableViewCell")
@interface PaymentDateTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PaymentIDTableViewCell")
@interface PaymentIDTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PaymentMethod")
@interface PaymentMethod : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified name;
@property (nonatomic, copy) NSString * _Null_unspecified paymentTypeId;
@property (nonatomic, copy) NSArray<Setting *> * _Null_unspecified settings;
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified additionalInfoNeeded;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isIssuerRequired;
- (BOOL)isIdentificationRequired;
- (BOOL)isIdentificationTypeRequired;
- (BOOL)isCard;
- (BOOL)isSecurityCodeRequired:(NSString * _Nonnull)bin;
- (BOOL)isAdditionalInfoNeeded:(NSString * _Null_unspecified)param;
- (NSString * _Nonnull)toJSONString;
+ (PaymentMethod * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (BOOL)conformsToBIN:(NSString * _Nonnull)bin;
- (PaymentMethod * _Nullable)cloneWithBIN:(NSString * _Nonnull)bin;
- (BOOL)isAmex;
- (BOOL)secCodeMandatory;
- (NSInteger)secCodeLenght;
- (NSInteger)cardNumberLenght;
- (BOOL)secCodeInBack;
- (BOOL)isOfflinePaymentMethod;
- (BOOL)isVISA;
- (BOOL)isMASTERCARD;
- (BOOL)conformsPaymentPreferences:(PaymentPreference * _Nullable)paymentPreference;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK16PaymentMethodRow")
@interface PaymentMethodRow : NSObject
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic, strong) Card * _Nullable card;
@property (nonatomic, copy) NSString * _Nullable icon;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentMethodSearchService")
@interface PaymentMethodSearchService : MercadoPagoService
@property (nonatomic, readonly, copy) NSString * _Nonnull MP_SEARCH_PAYMENTS_URI;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentMethodTableViewCell")
@interface PaymentMethodTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setLabel:(NSString * _Nonnull)label;
- (void)setImageWithName:(NSString * _Nonnull)imageName;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK28PaymentMethodsViewController")
@interface PaymentMethodsViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK17PaymentPreference")
@interface PaymentPreference : NSObject
@property (nonatomic, copy) NSSet<NSString *> * _Nullable excludedPaymentMethodIds;
@property (nonatomic, copy) NSSet<NSString *> * _Nullable excludedPaymentTypeIds;
@property (nonatomic, copy) NSString * _Nullable defaultPaymentMethodId;
@property (nonatomic) NSInteger maxAcceptedInstallments;
@property (nonatomic) NSInteger defaultInstallments;
@property (nonatomic, copy) NSString * _Nullable defaultPaymentTypeId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (PayerCost * _Nullable)autoSelectPayerCost:(NSArray<PayerCost *> * _Nonnull)payerCostList;
- (BOOL)validate;
+ (PaymentPreference * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14PaymentService")
@interface PaymentService : MercadoPagoService
- (void)getPaymentMethods:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nonnull)public_key success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
- (void)getInstallments:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nonnull)public_key bin:(NSString * _Nullable)bin amount:(double)amount issuer_id:(NSNumber * _Nullable)issuer_id payment_method_id:(NSString * _Nonnull)payment_method_id success:(void (^ _Nonnull)(NSArray<Installment *> * _Nonnull))success failure:(void (^ _Nonnull)(NSError * _Nonnull error))failure;
- (void)getIssuers:(NSString * _Nonnull)method uri:(NSString * _Nonnull)uri public_key:(NSString * _Nonnull)public_key payment_method_id:(NSString * _Nonnull)payment_method_id bin:(NSString * _Nullable)bin success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK25PaymentTotalTableViewCell")
@interface PaymentTotalTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK11PaymentType")
@interface PaymentType : NSObject
+ (NSSet<NSString *> * _Nonnull)allPaymentIDs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (PaymentType * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK26PaymentVaultViewController")
@interface PaymentVaultViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nonnull instancetype)initWithAmount:(double)amount paymentPreference:(PaymentPreference * _Nullable)paymentPreference callback:(void (^ _Nonnull)(PaymentMethod * _Nonnull paymentMethod, Token * _Nullable token, Issuer * _Nullable issuer, PayerCost * _Nullable payerCost))callback callbackCancel:(void (^ _Nullable)(void))callbackCancel OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)didReceiveMemoryWarning;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK34PreferenceDescriptionTableViewCell")
@interface PreferenceDescriptionTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK17PreferenceService")
@interface PreferenceService : MercadoPagoService
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK5Promo")
@interface Promo : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified promoId;
@property (nonatomic, strong) Issuer * _Null_unspecified issuer;
@property (nonatomic, copy) NSString * _Null_unspecified recommendedMessage;
@property (nonatomic, copy) NSArray<PaymentMethod *> * _Null_unspecified paymentMethods;
@property (nonatomic, copy) NSString * _Null_unspecified legals;
@property (nonatomic, copy) NSString * _Nullable url;
+ (Promo * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
+ (NSDate * _Null_unspecified)getDateFromString:(NSString * _Null_unspecified)string;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromoEmptyTableViewCell")
@interface PromoEmptyTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImageView;

SWIFT_CLASS("_TtC14MercadoPagoSDK18PromoTableViewCell")
@interface PromoTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified issuerImageView;
@property (nonatomic, weak) IBOutlet MPLabel * _Null_unspecified sharesSubtitle;
@property (nonatomic, weak) IBOutlet MPLabel * _Null_unspecified paymentMethodsSubtitle;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Null_unspecified)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setPromoInfo:(Promo * _Null_unspecified)promo;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK27PromoTyCDetailTableViewCell")
@interface PromoTyCDetailTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)setLabelWithIssuerName:(NSString * _Nonnull)issuer legals:(NSString * _Nullable)legals;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19PromoViewController")
@interface PromoViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, readonly, copy) NSString * _Nonnull screenName;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCallback:(void (^ _Nullable)(void))callback OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)back;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK13PromosService")
@interface PromosService : MercadoPagoService
- (void)getPromos:(NSString * _Nonnull)url method:(NSString * _Nonnull)method public_key:(NSString * _Nonnull)public_key success:(void (^ _Nonnull)(id _Nullable jsonResult))success failure:(void (^ _Nullable)(NSError * _Nonnull error))failure;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK22PromosTyCTableViewCell")
@interface PromosTyCTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK23PromosTyCViewController")
@interface PromosTyCViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (nonnull instancetype)initWithPromos:(NSArray<Promo *> * _Nonnull)promos OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK6Refund")
@interface Refund : NSObject
@property (nonatomic) double amount;
@property (nonatomic, strong) NSDate * _Null_unspecified dateCreated;
@property (nonatomic) NSInteger _id;
@property (nonatomic, strong) NSObject * _Null_unspecified metadata;
@property (nonatomic) NSInteger paymentId;
@property (nonatomic, copy) NSString * _Null_unspecified source;
@property (nonatomic, copy) NSString * _Null_unspecified uniqueSequenceNumber;
+ (Refund * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK14SavedCardToken")
@interface SavedCardToken : NSObject
@property (nonatomic, copy) NSString * _Nullable cardId;
@property (nonatomic, copy) NSString * _Nullable securityCode;
@property (nonatomic, strong) Device * _Nullable device;
@property (nonatomic) BOOL securityCodeRequired;
- (nonnull instancetype)initWithCardId:(NSString * _Nonnull)cardId securityCode:(NSString * _Nonnull)securityCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCard:(Card * _Nonnull)card securityCode:(NSString * _Nullable)securityCode securityCodeRequired:(BOOL)securityCodeRequired OBJC_DESIGNATED_INITIALIZER;
- (BOOL)validate;
- (BOOL)validateCardId;
- (BOOL)validateSecurityCode;
- (NSString * _Nonnull)toJSONString;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK12SecurityCode")
@interface SecurityCode : NSObject
@property (nonatomic) NSInteger length;
@property (nonatomic, copy) NSString * _Null_unspecified cardLocation;
@property (nonatomic, copy) NSString * _Null_unspecified mode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (SecurityCode * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
@end

@class NSData;

SWIFT_CLASS("_TtC14MercadoPagoSDK12Serializable")
@interface Serializable : NSObject

/// Converts the class to a dictionary.
///
/// \returns  The class as an NSDictionary.
- (NSDictionary * _Nonnull)toDictionary;

/// Converts the class to JSON.
///
/// \returns  The class as JSON, wrapped in NSData.
- (NSData * _Nullable)toJson:(BOOL)prettyPrinted;

/// Converts the class to a JSON string.
///
/// \returns  The class as a JSON string.
- (NSString * _Nullable)toJsonString:(BOOL)prettyPrinted;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface Serializable (SWIFT_EXTENSION(MercadoPagoSDK))
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK7Setting")
@interface Setting : NSObject
@property (nonatomic, strong) BinMask * _Null_unspecified binMask;
@property (nonatomic, strong) CardNumber * _Null_unspecified cardNumber;
@property (nonatomic, strong) SecurityCode * _Null_unspecified securityCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (Setting * _Nullable)getSettingByBin:(NSArray<Setting *> * _Null_unspecified)settings bin:(NSString * _Null_unspecified)bin;
+ (Setting * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end



SWIFT_CLASS("_TtC14MercadoPagoSDK5Token")
@interface Token : NSObject
@property (nonatomic, copy) NSString * _Null_unspecified _id;
@property (nonatomic, copy) NSString * _Null_unspecified publicKey;
@property (nonatomic, copy) NSString * _Null_unspecified cardId;
@property (nonatomic, copy) NSString * _Null_unspecified luhnValidation;
@property (nonatomic, copy) NSString * _Null_unspecified status;
@property (nonatomic, copy) NSString * _Null_unspecified usedDate;
@property (nonatomic) NSInteger cardNumberLength;
@property (nonatomic, strong) NSDate * _Null_unspecified creationDate;
@property (nonatomic, copy) NSString * _Null_unspecified lastFourDigits;
@property (nonatomic, copy) NSString * _Null_unspecified firstSixDigit;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic) NSInteger expirationMonth;
@property (nonatomic) NSInteger expirationYear;
@property (nonatomic, strong) NSDate * _Null_unspecified lastModifiedDate;
@property (nonatomic, strong) NSDate * _Null_unspecified dueDate;
@property (nonatomic, strong) Cardholder * _Nullable cardHolder;
- (nonnull instancetype)initWith_id:(NSString * _Nonnull)_id publicKey:(NSString * _Nonnull)publicKey cardId:(NSString * _Null_unspecified)cardId luhnValidation:(NSString * _Null_unspecified)luhnValidation status:(NSString * _Null_unspecified)status usedDate:(NSString * _Null_unspecified)usedDate cardNumberLength:(NSInteger)cardNumberLength creationDate:(NSDate * _Null_unspecified)creationDate lastFourDigits:(NSString * _Null_unspecified)lastFourDigits firstSixDigit:(NSString * _Null_unspecified)firstSixDigit securityCodeLength:(NSInteger)securityCodeLength expirationMonth:(NSInteger)expirationMonth expirationYear:(NSInteger)expirationYear lastModifiedDate:(NSDate * _Null_unspecified)lastModifiedDate dueDate:(NSDate * _Nullable)dueDate cardHolder:(Cardholder * _Nullable)cardHolder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)getBin;
+ (Token * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
- (NSString * _Nonnull)toJSONString;
- (NSString * _Nonnull)getCardExpirationDateFormated;
- (NSString * _Nonnull)getMaskNumber;
- (NSString * _Nonnull)getExpirationDateFormated;
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK18TransactionDetails")
@interface TransactionDetails : NSObject
@property (nonatomic) double couponAmount;
@property (nonatomic, copy) NSString * _Null_unspecified externalResourceUrl;
@property (nonatomic, copy) NSString * _Null_unspecified financialInstitution;
@property (nonatomic) double installmentAmount;
@property (nonatomic) double netReceivedAmount;
@property (nonatomic) double overpaidAmount;
@property (nonatomic) double totalPaidAmount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (TransactionDetails * _Nonnull)fromJSON:(NSDictionary * _Nonnull)json;
@end


@interface UIColor (SWIFT_EXTENSION(MercadoPagoSDK))
+ (UIColor * _Nonnull)UIColorFromRGB:(NSUInteger)rgbValue;
+ (UIColor * _Nonnull)mpDefaultColor;
+ (UIColor * _Nonnull)errorCellColor;
+ (UIColor * _Nonnull)greenOkColor;
+ (UIColor * _Nonnull)redFailureColor;
+ (UIColor * _Nonnull)errorValidationTextColor;
+ (UIColor * _Nonnull)yellowFailureColor;
+ (UIColor * _Nonnull)blueMercadoPago;
+ (UIColor * _Nonnull)grayBaseText;
+ (UIColor * _Nonnull)grayDark;
+ (UIColor * _Nonnull)grayLight;
+ (UIColor * _Nonnull)grayLines;
+ (UIColor * _Nonnull)grayTableSeparator;
+ (UIColor * _Nonnull)backgroundColor;
+ (UIColor * _Nonnull)white;
+ (UIColor * _Nonnull)installments;
+ (UIColor * _Nonnull)systemFontColor;
+ (UIColor * _Nonnull)primaryColor;
+ (UIColor * _Nonnull)complementaryColor;
@end


@interface UIDevice (SWIFT_EXTENSION(MercadoPagoSDK))
@end

@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC14MercadoPagoSDK13UILoadingView")
@interface UILoadingView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)rect text:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) MPLabel * _Nonnull label;
@property (nonatomic, strong) UIActivityIndicatorView * _Nonnull spinner;
- (void)layoutSubviews;
@end


@interface UINavigationBar (SWIFT_EXTENSION(MercadoPagoSDK))
@end


@interface UINavigationController (SWIFT_EXTENSION(MercadoPagoSDK))
- (BOOL)shouldAutorotate;
- (UIInterfaceOrientationMask)supportedInterfaceOrientations;
@end


@interface UIView (SWIFT_EXTENSION(MercadoPagoSDK))
@end


SWIFT_CLASS("_TtC14MercadoPagoSDK19VaultViewController")
@interface VaultViewController : MercadoPagoUIViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, copy) void (^ _Nullable callback)(PaymentMethod * _Nonnull paymentMethod, NSString * _Nullable tokenId, Issuer * _Nullable issuer, NSInteger installments);
@property (nonatomic, strong) UILoadingView * _Null_unspecified loadingView;
@property (nonatomic, strong) Card * _Nullable selectedCard;
@property (nonatomic, strong) PayerCost * _Nullable selectedPayerCost;
@property (nonatomic, strong) CardToken * _Nullable selectedCardToken;
@property (nonatomic, strong) PaymentMethod * _Nullable selectedPaymentMethod;
@property (nonatomic, strong) Issuer * _Nullable selectedIssuer;
@property (nonatomic, copy) NSArray<Card *> * _Nullable cards;
@property (nonatomic, copy) NSArray<PayerCost *> * _Nullable payerCosts;
@property (nonatomic) BOOL securityCodeRequired;
@property (nonatomic) NSInteger securityCodeLength;
@property (nonatomic, copy) NSString * _Nullable bin;
@property (nonatomic, strong) PaymentPreference * _Nullable paymentPreference;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)scrollToRow:(NSIndexPath * _Nonnull)indexPath;
- (void)declareAndInitCells;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)showViewController:(UIViewController * _Nonnull)vc;
- (void)loadPayerCosts;
- (void)submitForm;
@end

#pragma clang diagnostic pop
